name: Update ODH Model Controller Runtime Versions

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to create PR against'
        required: true
        default: 'main'
        type: string
      runtime_filter:
        description: 'Filter specific runtime (optional, select "all" for all runtimes)'
        required: false
        type: choice
        default: 'all'
        options:
          - 'all'
          - 'vllm'
          - 'vllm-rocm' 
          - 'vllm-cpu'
          - 'vllm-gaudi'
          - 'ovms'
      dry_run:
        description: 'Dry run - show changes without creating PRs'
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      target_branch:
        description: 'Target branch to create PR against'
        required: true
        type: string
      runtime_filter:
        description: 'Filter specific runtime'
        required: false
        type: string
        default: 'all'
      dry_run:
        description: 'Dry run - show changes without creating PRs'
        required: false
        type: boolean
        default: false
    secrets:
      gh_token:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.RHOAI_ACTION_SECRET || secrets.gh_token }}

jobs:
  update-odh-runtime-versions:
    runs-on: ubuntu-latest
    
    outputs:
      summary: ${{ steps.update.outputs.summary }}
      pr_url: ${{ steps.update.outputs.pr_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML requests
        
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Update ODH Model Controller runtime versions
      id: update
      env:
        TARGET_BRANCH: ${{ inputs.target_branch }}
        RUNTIME_FILTER: ${{ inputs.runtime_filter }}
        DRY_RUN: ${{ inputs.dry_run }}
      run: |
        python .github/scripts/update_odh_runtime_versions.py
        
        # Set outputs
        if [ -f odh_update_summary.md ]; then
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          cat odh_update_summary.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi
        
        if [ -f pr_url.txt ]; then
          echo "pr_url=$(cat pr_url.txt)" >> $GITHUB_OUTPUT
        fi
        
    - name: Summary
      run: |
        echo "## ODH Model Controller Update Summary" >> $GITHUB_STEP_SUMMARY
        if [ -f odh_update_summary.md ]; then
          cat odh_update_summary.md >> $GITHUB_STEP_SUMMARY
        else
          echo "No updates were processed." >> $GITHUB_STEP_SUMMARY
        fi
